// Single source of truth for the "Vibrant" per-cuisine visual theme.
// `vars` are applied as CSS custom properties on the document root; everything
// else (greeting, emoji, stripe/number colors) is consumed directly by components.

export const DEFAULT_CUISINE = "Indian";

export const CUISINE_THEMES = {
  Indian: {
    vars: {
      "--bg-page": "#FFF4E2",
      "--bg-surface": "#FFFDF7",
      "--border": "#F0DFBE",
      "--text": "#3B2410",
      "--text-dim": "#8A6A3F",
      "--accent-a": "#3E8E5A",
      "--accent-b": "#E04B2A",
      "--accent-c": "#F2A007",
      "--cuisine-pill-active-bg": "#F2A007",
      "--mode-cook-bg": "#3E8E5A",
      "--mode-eatout-bg": "#F2A007",
      "--on-accent": "#FFF8EA",
      "--badge-bg": "#FFE8BE",
      "--badge-text": "#8A5A00",
      "--note-bg": "#EAF4E7",
      "--ingredient-bg": "#FCF6E8",
      "--heat-box-bg": "#FFF1D6",
      "--heat-label": "#A87F3F",
      "--greeting": "#E04B2A",
    },
    greeting: "Garma garam!",
    emoji: "🌶️",
    stripe: ["#F2A007", "#E04B2A", "#3E8E5A"],
    numberColors: ["#F2A007", "#E04B2A", "#3E8E5A"],
    numberText: "#FFF8EA",
  },

  Italian: {
    vars: {
      "--bg-page": "#FFF8EF",
      "--bg-surface": "#FFFDF9",
      "--border": "#F0E2C8",
      "--text": "#33231A",
      "--text-dim": "#9A7B5F",
      "--accent-a": "#3E8E5A",
      "--accent-b": "#D93A2B",
      "--accent-c": "#F2A007",
      "--cuisine-pill-active-bg": "#3E8E5A",
      "--mode-cook-bg": "#3E8E5A",
      "--mode-eatout-bg": "#D93A2B",
      "--on-accent": "#FFF8EF",
      "--badge-bg": "#FBEBD3",
      "--badge-text": "#9A6A1F",
      "--note-bg": "#EAF4E7",
      "--ingredient-bg": "#FAF1E2",
      "--heat-box-bg": "#FBEBD3",
      "--heat-label": "#9A7B5F",
      "--greeting": "#D93A2B",
    },
    greeting: "Mangia! Mangia!",
    emoji: "🍝",
    stripe: ["#3E8E5A", "#FFFDF9", "#D93A2B"],
    numberColors: ["#3E8E5A", "#D93A2B"],
    numberText: "#FFF8EF",
  },

  Mexican: {
    vars: {
      "--bg-page": "#2B1240",
      "--bg-surface": "#38195A",
      "--border": "#4E2A70",
      "--text": "#FFF3E4",
      "--text-dim": "#C9A8E8",
      "--accent-a": "#A9E34B",
      "--accent-b": "#FF4D8D",
      "--accent-c": "#FFC93C",
      "--cuisine-pill-active-bg": "#FF4D8D",
      "--mode-cook-bg": "#A9E34B",
      "--mode-eatout-bg": "#FFC93C",
      "--on-accent": "#2B1240",
      "--badge-bg": "#4E2A70",
      "--badge-text": "#FFC93C",
      "--note-bg": "#452066",
      "--ingredient-bg": "#452066",
      "--heat-box-bg": "#452066",
      "--heat-label": "#C9A8E8",
      "--greeting": "#FFC93C",
    },
    greeting: "¡Buen provecho!",
    emoji: "🌮",
    stripe: ["#FF4D8D", "#FFC93C", "#A9E34B", "#4DD6C1"],
    numberColors: ["#FF4D8D", "#FFC93C", "#A9E34B", "#4DD6C1"],
    numberText: "#2B1240",
  },

  Chinese: {
    vars: {
      "--bg-page": "#FFF5EA",
      "--bg-surface": "#FFFDF8",
      "--border": "#F2DFC6",
      "--text": "#2E1F1A",
      "--text-dim": "#8A6A50",
      "--accent-a": "#2E9E6B",
      "--accent-b": "#D7263D",
      "--accent-c": "#DFA32B",
      "--cuisine-pill-active-bg": "#D7263D",
      "--mode-cook-bg": "#2E9E6B",
      "--mode-eatout-bg": "#DFA32B",
      "--on-accent": "#FFFDF8",
      "--badge-bg": "#FBE5D2",
      "--badge-text": "#A25617",
      "--note-bg": "#E7F3EC",
      "--ingredient-bg": "#FAF0E4",
      "--heat-box-bg": "#FDEBDD",
      "--heat-label": "#A2785A",
      "--greeting": "#D7263D",
    },
    greeting: "Mànmàn chī!",
    emoji: "🥟",
    stripe: ["#D7263D", "#DFA32B", "#2E9E6B"],
    numberColors: ["#D7263D", "#DFA32B", "#2E9E6B"],
    numberText: "#FFFDF8",
  },

  Japanese: {
    vars: {
      "--bg-page": "#F2F5EC",
      "--bg-surface": "#FFFFFF",
      "--border": "#DCE5D2",
      "--text": "#22302C",
      "--text-dim": "#5E7268",
      "--accent-a": "#7BAE3F",
      "--accent-b": "#E5484D",
      "--accent-c": "#3B4C9B",
      "--cuisine-pill-active-bg": "#3B4C9B",
      "--mode-cook-bg": "#7BAE3F",
      "--mode-eatout-bg": "#3B4C9B",
      "--on-accent": "#FFFFFF",
      "--badge-bg": "#EEF1FB",
      "--badge-text": "#3B4C9B",
      "--note-bg": "#EEF1FB",
      "--ingredient-bg": "#F5F9F0",
      "--heat-box-bg": "#FFF3D6",
      "--heat-label": "#A8632A",
      "--greeting": "#E5484D",
    },
    greeting: "Itadakimasu!",
    emoji: "🍣",
    stripe: ["#E5484D", "#7BAE3F", "#3B4C9B"],
    numberColors: ["#E5484D", "#7BAE3F", "#3B4C9B"],
    numberText: "#FFFFFF",
  },

  Thai: {
    vars: {
      "--bg-page": "#FFF6EA",
      "--bg-surface": "#FFFDF7",
      "--border": "#F2E0C4",
      "--text": "#33231A",
      "--text-dim": "#9A7B5F",
      "--accent-a": "#8CB92E",
      "--accent-b": "#D6336C",
      "--accent-c": "#F2A007",
      "--cuisine-pill-active-bg": "#D6336C",
      "--mode-cook-bg": "#8CB92E",
      "--mode-eatout-bg": "#D6336C",
      "--on-accent": "#FFFDF7",
      "--badge-bg": "#F7E7EE",
      "--badge-text": "#A6265A",
      "--note-bg": "#F7E7EE",
      "--ingredient-bg": "#FBF0DF",
      "--heat-box-bg": "#FCEFD8",
      "--heat-label": "#A87F3F",
      "--greeting": "#D6336C",
    },
    greeting: "Aròi mâak!",
    emoji: "🍜",
    stripe: ["#D6336C", "#F2A007", "#8CB92E"],
    numberColors: ["#D6336C", "#F2A007", "#8CB92E"],
    numberText: "#FFFDF7",
  },

  Mediterranean: {
    vars: {
      "--bg-page": "#F2F7FA",
      "--bg-surface": "#FFFFFF",
      "--border": "#D8E4EC",
      "--text": "#223744",
      "--text-dim": "#5A7A93",
      "--accent-a": "#2E6FB7",
      "--accent-b": "#D97742",
      "--accent-c": "#7E8E3C",
      "--cuisine-pill-active-bg": "#2E6FB7",
      "--mode-cook-bg": "#2E6FB7",
      "--mode-eatout-bg": "#D97742",
      "--on-accent": "#FFFFFF",
      "--badge-bg": "#EAF2F8",
      "--badge-text": "#2E6FB7",
      "--note-bg": "#F6EFE7",
      "--ingredient-bg": "#EFF5F9",
      "--heat-box-bg": "#EAF2F8",
      "--heat-label": "#5A7A93",
      "--greeting": "#D97742",
    },
    greeting: "Opa!",
    emoji: "🫒",
    stripe: ["#2E6FB7", "#D97742", "#7E8E3C"],
    numberColors: ["#2E6FB7", "#D97742", "#7E8E3C"],
    numberText: "#FFFFFF",
  },

  French: {
    vars: {
      "--bg-page": "#FFF9F2",
      "--bg-surface": "#FFFEFB",
      "--border": "#EEE0CE",
      "--text": "#2E2620",
      "--text-dim": "#8C7A66",
      "--accent-a": "#3B5BA5",
      "--accent-b": "#8E2F3C",
      "--accent-c": "#C7212B",
      "--cuisine-pill-active-bg": "#3B5BA5",
      "--mode-cook-bg": "#3B5BA5",
      "--mode-eatout-bg": "#8E2F3C",
      "--on-accent": "#FFFEFB",
      "--badge-bg": "#F3E9EA",
      "--badge-text": "#8E2F3C",
      "--note-bg": "#F3E9EA",
      "--ingredient-bg": "#F7F0E6",
      "--heat-box-bg": "#F7EEE2",
      "--heat-label": "#9A8468",
      "--greeting": "#8E2F3C",
    },
    greeting: "Bon appétit!",
    emoji: "🥐",
    stripe: ["#3B5BA5", "#FFFEFB", "#C7212B"],
    numberColors: ["#3B5BA5", "#C7212B"],
    numberText: "#FFFEFB",
  },

  "American Diner": {
    vars: {
      "--bg-page": "#E8F5EF",
      "--bg-surface": "#FFFDF6",
      "--border": "#D9E8DE",
      "--text": "#2A2622",
      "--text-dim": "#8A7A66",
      "--accent-a": "#2FB5A3",
      "--accent-b": "#E0432D",
      "--accent-c": "#1F8A7A",
      "--cuisine-pill-active-bg": "#E0432D",
      "--mode-cook-bg": "#2FB5A3",
      "--mode-eatout-bg": "#E0432D",
      "--on-accent": "#FFFDF6",
      "--badge-bg": "#E4F3EE",
      "--badge-text": "#1F8A7A",
      "--note-bg": "#E4F3EE",
      "--ingredient-bg": "#F6F3EA",
      "--heat-box-bg": "#FDF0DC",
      "--heat-label": "#A8895A",
      "--greeting": "#E0432D",
    },
    greeting: "Order's up!",
    emoji: "🥞",
    stripe: ["#E0432D", "#FFFDF6", "#2FB5A3", "#FFFDF6", "#E0432D"],
    numberColors: ["#E0432D", "#2FB5A3"],
    numberText: "#FFFDF6",
  },
};

export function resolveCuisineKey(name) {
  if (!name) return DEFAULT_CUISINE;
  const trimmed = name.trim().toLowerCase();
  const match = Object.keys(CUISINE_THEMES).find((k) => k.toLowerCase() === trimmed);
  return match || DEFAULT_CUISINE;
}

export function getCuisineTheme(name) {
  return CUISINE_THEMES[resolveCuisineKey(name)];
}
